
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 24 14:24:16 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 23;
  public static final int NAMESPACE = 38;
  public static final int SLASH = 37;
  public static final int EQUALS = 30;
  public static final int NUMCONST = 48;
  public static final int NOTEQUAL = 39;
  public static final int CONTINUE = 43;
  public static final int GREATER = 36;
  public static final int LPAREN = 4;
  public static final int LESS = 25;
  public static final int FOR = 13;
  public static final int MINUS = 22;
  public static final int STATIC = 14;
  public static final int RPAREN = 5;
  public static final int SEMICOLON = 15;
  public static final int AND = 24;
  public static final int RANGE = 53;
  public static final int OR = 44;
  public static final int IN = 2;
  public static final int COMMA = 9;
  public static final int CLASS = 41;
  public static final int INC = 32;
  public static final int GEQ = 33;
  public static final int PLUS = 8;
  public static final int IF = 51;
  public static final int ASSIGN = 21;
  public static final int THIS = 34;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int EQUAL = 6;
  public static final int LAMBDA = 27;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int LCURLY = 20;
  public static final int PERCENT = 18;
  public static final int NUMBER = 46;
  public static final int IDENT = 47;
  public static final int BREAK = 29;
  public static final int VOID = 11;
  public static final int RCURLY = 40;
  public static final int TIMES = 28;
  public static final int COLON = 12;
  public static final int ELSE = 52;
  public static final int LSQUARE = 26;
  public static final int READ = 31;
  public static final int CHARCONST = 49;
  public static final int RSQUARE = 42;
  public static final int BOOLCONST = 50;
  public static final int EXTENDS = 16;
  public static final int PROG = 3;
  public static final int LEQ = 35;
  public static final int DEC = 45;
  public static final int PRINT = 10;
}

